### ISSUE TITLE
Allow case insensitive file list

### ISSUE THREAD

**Issue by j1warren** [jonniek/mpv-nextfile#15]
Would be nice to have a flag to change the file list to become case insensitive.

**Comment by Mehvix** [comment]
I fixed this by removing the `v` flag from the `ls` command on line 63:

https://github.com/jonniek/mpv-nextfile/blob/b6999a810af72fb55bf0c577875916b467b6b194/nextfile.lua#L63

to get 

```lua
 local args = { 'ls', '-1p', dir } 
```
