### ISSUE TITLE
Setting Page Down = Next Shortcut Key but failed!

### ISSUE THREAD

**Issue by NevGi-cpu** [jonniek/mpv-nextfile#16]
I am using this script for celluloid as a plugin.

I changed the last two lines to:
mp.add_key_binding('PgDown', 'nextfile', nexthandler)
mp.add_key_binding('PgUp', 'previousfile', prevhandler)

Problem:
Page Up/Page Down was by default used for seeking video forward/backward in celluloid. but since I can use Page Up just fine for  playing prev file in current directiry I was hoping if there is any way I can use Page Down for playing next file in current directory.

**Comment by jonniek** [comment]
Does it work with any other keybind?

**Comment by AliReza99** [comment]
@NevGi-cpu 
you should use 'PGUP' , 'PGDWN' instead
