### ISSUE TITLE
Doesnt work at all

### ISSUE THREAD

**Issue by darkdream787** [jonniek/mpv-nextfile#18]
I have installed the script properly, as any other script I am using works fine. I am using a recent version of MPV.

It doesn't matter what I keybind this to in the input.conf file, it does absolutely nothing for me. 
Also, if I keybind it to something that was being used for something else, it just disables it, and the button no longer does anything at all.

I tried making a script-opts file as well with the keybinds and that doesn't work either.

**Comment by darkdream787** [comment]
This appears to be what the log/console was saying.


[   4.185][e][nextfile]           Trap {
[   4.185][e][nextfile]               Write-Error -ErrorRecord $_
[   4.185][e][nextfile]               Exit 1
[   4.186][e][nextfile]           }
[   4.186][e][nextfile]           $path = "L:\TV Shows\"
[   4.186][e][nextfile]           $escapedPath = [WildcardPattern]::Escape($path)
[   4.186][e][nextfile]           cd $escapedPath
[   4.186][e][nextfile]     
[   4.186][e][nextfile]           $list = (Get-ChildItem -File | Sort-Object { [regex]::Replace($_.Name
[   4.186][e][nextfile] , '\d+', { $args[0].Value.PadLeft(20) }) }).Name
[   4.186][e][nextfile]           $string = ($list -join "/")
[   4.186][e][nextfile]           $u8list = [System.Text.Encoding]::UTF8.GetBytes($string)
[   4.186][e][nextfile]           [Console]::OpenStandardOutput().Write($u8list, 0, $u8list.Length)
[   4.186][e][nextfile]        : Unable to find type [WildcardPattern]: make sure that the assembly con
[   4.186][e][nextfile] taining this type is loaded.
[   4.186][e][nextfile] At line:1 char:2
[   4.186][e][nextfile] + & <<<<  {
[   4.186][e][nextfile]     + CategoryInfo          : InvalidOperation: (WildcardPattern:String) [Writ 
[   4.186][e][nextfile]    e-Error], RuntimeException
[   4.186][e][nextfile]     + FullyQualifiedErrorId : TypeNotFound
[   4.186][e][nextfile]  
[   4.198][e][nextfile] Subprocess failed:

**Comment by darkdream787** [comment]
[   4.256][e][nextfile]           Trap {
[   4.256][e][nextfile]               Write-Error -ErrorRecord $_
[   4.256][e][nextfile]               Exit 1
[   4.256][e][nextfile]           }
[   4.256][e][nextfile]           cd "L:\TV Shows\ReBoot\"
[   4.256][e][nextfile]           $list = (Get-ChildItem -File | Sort-Object { [regex]::Replace($_.Name
[   4.256][e][nextfile] , '\d+', { $args[0].Value.PadLeft(20) }) }).Name
[   4.256][e][nextfile]           $string = ($list -join "/")
[   4.256][e][nextfile]           $u8list = [System.Text.Encoding]::UTF8.GetBytes($string)
[   4.256][e][nextfile]           [Console]::OpenStandardOutput().Write($u8list, 0, $u8list.Length)
[   4.256][e][nextfile]        : A parameter cannot be found that matches parameter name 'File'.
[   4.256][e][nextfile] At line:1 char:2
[   4.256][e][nextfile] + & <<<<  {
[   4.257][e][nextfile]     + CategoryInfo          : InvalidArgument: (:) [Write-Error], ParameterBin 
[   4.257][e][nextfile]    dingException
[   4.257][e][nextfile]     + FullyQualifiedErrorId : NamedParameterNotFound
[   4.257][e][nextfile]  
[   4.268][e][nextfile] Subprocess failed:

**Comment by darkdream787** [comment]
I tried it again with a different folder of files and this is the log/console


[   4.643][e][nextfile]           Trap {
[   4.643][e][nextfile]               Write-Error -ErrorRecord $_
[   4.643][e][nextfile]               Exit 1
[   4.643][e][nextfile]           }
[   4.643][e][nextfile]           $path = "L:\TV Shows\Hamtaro\Season 1\"
[   4.643][e][nextfile]           $escapedPath = [WildcardPattern]::Escape($path)
[   4.643][e][nextfile]           cd $escapedPath
[   4.643][e][nextfile]     
[   4.643][e][nextfile]           $list = (Get-ChildItem -File | Sort-Object { [regex]::Replace($_.Name
[   4.643][e][nextfile] , '\d+', { $args[0].Value.PadLeft(20) }) }).Name
[   4.644][e][nextfile]           $string = ($list -join "/")
[   4.644][e][nextfile]           $u8list = [System.Text.Encoding]::UTF8.GetBytes($string)
[   4.644][e][nextfile]           [Console]::OpenStandardOutput().Write($u8list, 0, $u8list.Length)
[   4.644][e][nextfile]        : Unable to find type [WildcardPattern]: make sure that the assembly con
[   4.644][e][nextfile] taining this type is loaded.
[   4.644][e][nextfile] At line:1 char:2
[   4.644][e][nextfile] + & <<<<  {
[   4.644][e][nextfile]     + CategoryInfo          : InvalidOperation: (WildcardPattern:String) [Writ 
[   4.644][e][nextfile]    e-Error], RuntimeException
[   4.644][e][nextfile]     + FullyQualifiedErrorId : TypeNotFound
[   4.644][e][nextfile]  
[   4.655][e][nextfile] Subprocess failed:

**Comment by darkdream787** [comment]
I finally got this to work. This script apparently has a dependency on a specific powershell version, or powershell in general.

I just installed the Windows Management Framework 5.1 update and it started working fine.

As of now you can get it here if anyone needs it - https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by jonniek** [comment]
Nice that you got it to work.

This script was written a long time ago so it has many hacks. Mpv has since improved their scripting APIs and this script should be rewritten to use those OS agnostic FS utils.
