### ISSUE TITLE
How to use that?

### ISSUE THREAD

**Issue by COLABORATI** [jonniek/mpv-nextfile#2]
Where do I need to copy this file? Please add at least one line of description how to use that script, not everybody has the ability to study mpv config options in depth, but still would like to have basic features enabled that makes it a little bit more usable. Thanks!

**Comment by jonniek** [comment]
[windows](https://mpv.io/manual/stable/#files-on-windows)  
[unix](https://mpv.io/manual/stable/#files)  
[input configuration](https://mpv.io/manual/stable/#input-conf)  

Let me know if you need more help.
