### ISSUE TITLE
Display filename by OSD when moving to next file [feature request]

### ISSUE THREAD

**Issue by kurtontheway** [jonniek/mpv-nextfile#5]
This script is pretty handy, I use it every day. Thanks, @jonniek !
The only thing I think it would be better if the file name display on screen when loading the next file.

**Comment by jonniek** [comment]
Can you confirm you want this behavior specifically for this script and not in general when a file is loaded? If the general solution is sufficient then adding `osd-playing-msg=${media-title}` to your `mpv.conf` should work.

If you prefer the behavior specifically for this script then I can add a setting for that.

**Comment by kurtontheway** [comment]
I’ll check it out and back to you, Thank you!

**Comment by kurtontheway** [comment]
That's exactly what I need, Thank you @jonniek !
