### ISSUE TITLE
Nextfile Closes mpv on Special Character ×

### ISSUE THREAD

**Issue by Eisa01** [jonniek/mpv-nextfile#6]
Hello Jonnie,

I have encountered another issue. 
It seems that the use of special characters in filenames will close mpv as it wont be able to find the next file.

Lets foresay that we r on foo×× S01E01, initiating Nextfile script will not be able to find foo×× S01E02, and it will close mpv.
Perhaps the issue is also there with other special characters.

Running: Windows 10 OS, mpv v0.29.1

Thanks again for this awesome script!
Regards,
Eisa

**Comment by jonniek** [comment]
This seems to be same issue as https://github.com/jonniek/mpv-playlistmanager/issues/9

I will try to look into listing files with utils or with powershell instead of cmd.

**Comment by jonniek** [comment]
Fixed in 2037030e215b002b9b98a6dd61aa461af5094309
