### ISSUE TITLE
Windows OS: Path with "[" breaks the script

### ISSUE THREAD

**Issue by Eisa01** [jonniek/mpv-nextfile#9]
In Windows OS, it seems that paths which include a square bracket "[", break the script e.g.:
`C:/Windows/[Test]/`

I believe this is due to powershell not taking the brackets as special character making it not part of the string.

**Comment by Eisa01** [comment]
Added pull request that should fix the issue, basically it escapes [ so it is read in the string

https://github.com/jonniek/mpv-nextfile/pull/10

**Comment by jonniek** [comment]
Thanks for the fix
